### ISSUE TITLE
Vendor Tasks Can be Combined

### ISSUE THREAD

**Issue by GarethOates** [duffers20/Angular2-Template#1]
Hey,

I wondered if instead of having individual gulp tasks for the vendor transfers to dist, you could instead create an array of paths, and use that array in 1 single gulp task which takes care of all the necessary vendors.  So instead of having many tasks with vendor: prefix, you simply have 1 vendor task with no dependencies on other tasks.  Since you don't need to minify or uglify any vendor libraries this should be doable.

Just a suggestion!

Gareth

**Comment by duffers20** [comment]
Hey! 

That's a good suggestion. When I put the script together in the first place, I didn't particularly like the way I had defined the individual vendor tasks, so I'm glad you've come up with a good suggestion.

I'll investigate using an array tomorrow at work. Also, feel free to submit changes!

James

**Comment by GarethOates** [comment]
Nice one! Will do! 😊👍🏻
